controller_list:
  - name: "manipulator"
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6, joint_7]

  - name: "manipulator_m"
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1_m, joint_2_m, joint_3_m, joint_4_m, joint_5_m, joint_6_m, joint_7_m]